package com.loadtest;

import com.loadtest.gwt.GwtXsrfServlet;
import com.loadtest.gwt.MyServiceImpl;
import org.springframework.boot.SpringApplication;
import org.springframework.boot.autoconfigure.SpringBootApplication;
import org.springframework.boot.web.servlet.ServletRegistrationBean;
import org.springframework.context.annotation.Bean;
import org.springframework.http.ResponseEntity;
import org.springframework.web.bind.annotation.*;

import javax.servlet.http.HttpSession;
import java.util.Map;

/**
 * Spring Boot host for real GWT-RPC servlets.
 *
 * Endpoints:
 *   POST /api/auth/login         — creates HttpSession; returns token for simulation compat
 *   GET  /app/mymodule.nocache.js — bootstrap file; simulation discovers policy from here
 *   POST /app/xsrf               — real XsrfTokenServiceServlet (gwt-servlet.jar)
 *   POST /app/open               — real XsrfProtectedServiceServlet (gwt-servlet.jar)
 *
 * Run:  mvn spring-boot:run   (port 8090)
 * Test: BASE_URL=http://localhost:8090 GWT_NOCACHE_JS_PATH=/app/mymodule.nocache.js \
 *       mvn -pl ../gatling gatling:test -Dgatling.simulationClass=simulations.GwtXsrfSimulation
 */
@SpringBootApplication
@RestController
public class GwtRpcDemoApp {

    // Policy strong name served in the .nocache.js bootstrap.
    // The simulation's "discover policy" step reads this value.
    // No GWT compilation needed — this is the only strong name the demo accepts
    // (doGetSerializationPolicy returns PermissivePolicy for any value).
    private static final String DEMO_POLICY = "AABBCCDDEEFF00112233445566778899";

    private static final Map<String, String> USERS = Map.of(
        "user1",  "pass1",  "user2",  "pass2",  "user3",  "pass3",
        "user4",  "pass4",  "user5",  "pass5",  "user6",  "pass6",
        "user7",  "pass7",  "user8",  "pass8",  "user9",  "pass9",
        "user10", "pass10"
    );

    public static void main(String[] args) {
        System.setProperty("server.port", "8090");
        SpringApplication.run(GwtRpcDemoApp.class, args);
    }

    // ── Real GWT-RPC servlet registrations ───────────────────────────────────

    @Bean
    public ServletRegistrationBean<GwtXsrfServlet> xsrfServletBean() {
        return new ServletRegistrationBean<>(new GwtXsrfServlet(), "/app/xsrf");
    }

    @Bean
    public ServletRegistrationBean<MyServiceImpl> myServiceBean() {
        return new ServletRegistrationBean<>(new MyServiceImpl(), "/app/open");
    }

    // ── Login: creates HttpSession (required by GWT XSRF) ────────────────────
    //
    // XsrfTokenServiceServlet generates the XSRF token from the session ID.
    // XsrfProtectedServiceServlet re-derives and validates using the same session.
    // Gatling carries the JSESSIONID cookie automatically per virtual user.
    @PostMapping("/api/auth/login")
    public ResponseEntity<?> login(@RequestBody Map<String, String> creds, HttpSession session) {
        String user = creds.getOrDefault("username", "");
        String pass = creds.getOrDefault("password", "");
        if (!USERS.containsKey(user) || !USERS.get(user).equals(pass)) {
            return ResponseEntity.status(401).body(Map.of("error", "Invalid credentials"));
        }
        session.setAttribute("username", user);
        // Return "token" so the simulation's saveAs("jwtToken") check succeeds.
        // The GWT servlets use the session cookie, not this token.
        return ResponseEntity.ok(Map.of("token", "session:" + session.getId().substring(0, 8)));
    }

    // ── .nocache.js bootstrap ─────────────────────────────────────────────────
    //
    // In a real GWT app this file is generated by the GWT compiler.
    // We serve a minimal version containing just the strong name so the
    // simulation's "discover policy" step works the same way against the demo
    // as it does against the real enterprise app.
    @GetMapping(value = "/app/mymodule.nocache.js", produces = "application/javascript")
    public String noCacheJs() {
        return "// GWT module bootstrap — policy strong name below\n"
             + "var strongName = '" + DEMO_POLICY + "';\n";
    }
}
